//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Safari/NSObject-Protocol.h>

@class BookmarksAutomationCommandRegistry;
@protocol BookmarksAutomationCommand, BookmarksAutomationEventListener;

@protocol BookmarksAutomationCommandRegistryEventListenerProvider <NSObject>
- (id <BookmarksAutomationEventListener>)bookmarksAutomationCommandRegistry:(BookmarksAutomationCommandRegistry *)arg1 eventListenerForCommand:(id <BookmarksAutomationCommand>)arg2;
@end

