//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <AppKit/NSTableCellView.h>

@class RolloverImageButton;

__attribute__((visibility("hidden")))
@interface SharedLinksFeedSubscriptionTableCellView : NSTableCellView
{
    RolloverImageButton *_removeButton;
}

@property(nonatomic) __weak RolloverImageButton *removeButton; // @synthesize removeButton=_removeButton;
- (void).cxx_destruct;
- (void)awakeFromNib;

@end

