//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Safari/RolloverActionButtonTableCellViewDelegate-Protocol.h>

@class NSString, NSTableCellView;

@protocol SidebarTableCellViewDelegate <RolloverActionButtonTableCellViewDelegate>
- (NSString *)accessibilityDescriptionForTableCellView:(NSTableCellView *)arg1;
- (void)didPressTableCellView:(NSTableCellView *)arg1;
@end

